# This is a basic workflow to help you get started with Actions

name: Python Actions

on:
 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:
  
  build:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v3

      
      - name: Build and push Image
        run: |
          echo "${{secrets.SEC_KEY}}" | docker login  -u "harinaru" --password=stdin
          docker image build -t harinaru/flaskapp_githubactions:v1 .
          docker push harinaru/flaskapp_githubactions:v1

      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
